/-
Completeness of the data-handling algebra.

Main Source:  Chapter 5 of F. A. N. Verri (2026). Data Science Project: An
Inductive Learning Approach. Version v1.0.0. Victoria, British Columbia, Canada:
Leanpub. doi: 10.5281/zenodo.14498010. url: https://leanpub.com/dsp.

This file makes precise the chapter's closing wish (its "future directions"
paragraph) for a notion of *completeness*: a strong argument that the proposed
operations can express all the useful changes one makes to a table.  We argue it
in two layers, after first rejecting the chapter's "Turing complete" framing.

## Why not "Turing complete"

"Expresses every transformation" is not a theorem one can state: the function
space `Table → Table` is uncountable and full of non-computable junk, and a
data-handling layer that was Turing complete would lose the totality and
optimizability that make it worth having.  Completeness is therefore always
stated *relative to a reference model*, exactly as Codd's "relational
completeness" is relative to the relational calculus.  The strength of the claim
equals the strength of the model it targets.

## Layer 1 -- expressive completeness (the reference model)

The data model here is a `K`-indexed family of multisets of records, i.e. a
*nested (grouped) bag relation*.  The accepted theory of "what a transformation
language on such data can do" is the **Nested Relational Calculus over the bag
monad with an aggregation fold** (bag-NRC + Σ), whose meta-theory is settled
(Buneman-Naqvi-Tannen-Wong; Libkin-Wong for bags + aggregates; Wong's
conservativity theorem).  At flat input/output it is provably equal to *bag
relational algebra with group-by/aggregate*, the expressive core of SQL, and it
subsumes the documented dataframe verb sets (Wickham's tidyverse; Petersohn's
pandas algebra).  bag-NRC + Σ is generated by a small fixed signature, and each
generator is one of our operations or a short pipeline:

| bag-NRC + Σ generator         | operation (in `Table.lean`)        |
| ----------------------------- | ---------------------------------- |
| empty, singleton, union `⊎`   | empty table, one-row table, `bind` |
| functorial map, tuple, π      | `map`                              |
| flatten `μ` (one level)       | `ungroup`                          |
| nest / group-by               | `project`                          |
| equality, conditional, filter | `map` with predicate body          |
| additive fold `Σ`             | `aggregate`                        |
| product / join                | `leftJoin` / `innerJoin`           |

`pivot` is then derived (nest-by-name then reshape) and so is anti-join /
difference (`antiJoin` below = `leftJoin` then filter on the unmatched side), so
nothing in the practical verb set is missing.  The `Verbs` section below
*exhibits* a representative slice of these verbs as definitions in the
primitives, with machine-checked split-safety where it holds, as the tangible
form of "all useful changes".

## Layer 2 -- safe completeness (the distinctive result)

Expressive completeness is table stakes.  The result tied to Mensura's purpose
is that the *split-invariant* operations express *exactly* the split-invariant
(leakage-safe) transformations, no more and no less.  Its backbone is the
structural fact that a key-preserving operation is split-invariant precisely when
it is **fiberwise** -- each output key reads only its own input key.  We package
that fiberwise shape as `fiberMap` and prove the characterization

    f is split-invariant and key-local  ↔  f = fiberMap Φ for a strict Φ
    (`splitInvariant_keyLocal_iff_fiberMap`)

so `fiberMap` is the *universal* safe key-preserving operation, and `map` (the
per-row, `BindHom` case) and `aggregate` (the whole-bag fold case) are its two
principal generators.  We also prove both hypotheses are necessary
(`fiberMap_nonstrict_not_splitInvariant`, `keySwap_not_keyLocal`), pinning the
boundary exactly.

## Honest scope

* Key-*changing* safe operations (`ungroup`, `project`, `unpivot`) are the graded
  generalization of `fiberMap`; the clean `iff` here is for the key-preserving
  fragment.
* Order-dependent verbs (window functions: `lag`, `cumsum`, `rank`) are not bag
  operations; they require lifting from the bag monad to the list monad (an
  explicit row-number index) and are out of scope, as in the chapter's
  "grouped and arranged" section.
* The unsafe escape hatches are already isolated in `Table.lean`:
  `project_not_preservesDisjoint` and `pivot_not_splitInvariant`.
-/

import Mensura.Table
import Mathlib.Data.Multiset.Dedup

namespace Mensura

variable {K H : Type _} {σ : H → Type}
variable {H' : Type _} {σ' : H' → Type}
variable {U G : Type _} {τ : G → Type}
variable {V : Type}
variable {K' N D : Type _}

/-! ## The universal fiberwise operation -/

/-- A *fiber map*: the output bag at each key is a function of the input bag at
the *same* key, and nothing else.  This is the universal shape of a
key-preserving split-invariant operation (`splitInvariant_keyLocal_iff_fiberMap`):
`map` and `aggregate` are both `fiberMap`s. -/
def fiberMap (Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')) (T : Table K H σ) :
    Table K H' σ' :=
  ⟨fun k => Φ k (T.rows k)⟩

/-- A fiber action is *strict* when it sends the empty bag to the empty bag (it
does not fabricate rows for an absent key).  Strictness is exactly what makes a
`fiberMap` split-invariant. -/
def Strict (Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')) : Prop :=
  ∀ k, Φ k 0 = 0

/-- A key-preserving operation is *key-local* when each output key depends only on
the input at that same key.  This is the second ingredient of the
characterization: split-invariance forbids reading across keys *additively*, but
not, on its own, key relabelings (`keySwap_not_keyLocal`); key-locality rules
those out, leaving exactly the fiber maps. -/
def KeyLocal (f : Table K H σ → Table K H' σ') : Prop :=
  ∀ (T T' : Table K H σ) (k : K), T.rows k = T'.rows k → (f T).rows k = (f T').rows k

/-- `map` is a fiber map: per-row `Multiset.bind` of the input bag. -/
theorem map_eq_fiberMap (φ : K → Row H σ → Multiset (Row H' σ')) :
    map φ = fiberMap (fun k m => m.bind (φ k)) := rfl

/-- `aggregate` is a fiber map: the whole-bag fold of the input bag. -/
theorem aggregate_eq_fiberMap (f : K → Multiset (Row H σ) → Row H σ) :
    aggregate f = fiberMap (fun k m => if m.card = 0 then 0 else {f k m}) := rfl

/-! ### A strict fiber map is split-safe -/

/-- A strict `fiberMap` is split-invariant: under disjointness one summand is
empty at each key, and strictness makes folding the union the same as folding the
nonempty side. -/
theorem fiberMap_splitInvariant {Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')}
    (hΦ : Strict Φ) : SplitInvariant (fiberMap Φ) := by
  intro T₀ T₁ hdisj
  apply Table.ext_rows
  intro k
  have hk := hΦ k
  simp only [fiberMap, bind]
  rcases hdisj k with h | h
  · rw [h]; simp [hk]
  · rw [h]; simp [hk]

/-- A strict `fiberMap` preserves disjointness: an empty input fiber stays empty. -/
theorem fiberMap_preservesDisjoint {Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')}
    (hΦ : Strict Φ) : PreservesDisjoint (fiberMap Φ) := by
  intro T₀ T₁ hdisj k
  rcases hdisj k with h | h
  · exact Or.inl (by simp [fiberMap, h, hΦ k])
  · exact Or.inr (by simp [fiberMap, h, hΦ k])

/-- Hence a strict `fiberMap` is `SplitSafe`, so it composes into pipelines that
stay split-invariant. -/
theorem fiberMap_splitSafe {Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')}
    (hΦ : Strict Φ) : SplitSafe (fiberMap Φ) :=
  ⟨fiberMap_preservesDisjoint hΦ, fiberMap_splitInvariant hΦ⟩

/-- Every `fiberMap` is key-local by construction. -/
theorem fiberMap_keyLocal (Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')) :
    KeyLocal (fiberMap Φ) := by
  intro T T' k h
  simp only [fiberMap]
  rw [h]

/-! ### Converse: every key-local split-invariant operation is a strict fiber map -/

/-- The table that holds `m` at key `k` and is empty elsewhere. -/
def pointTable [DecidableEq K] (k : K) (m : Multiset (Row H σ)) : Table K H σ :=
  ⟨fun k' => if k' = k then m else 0⟩

@[simp] theorem pointTable_rows_self [DecidableEq K] (k : K) (m : Multiset (Row H σ)) :
    (pointTable k m).rows k = m := by simp [pointTable]

/-- The fiber action *witnessed* by a key-local operation: run it on a table
supported at the single key `k`, and read off that key. -/
def fiberOf [DecidableEq K] (f : Table K H σ → Table K H' σ')
    (k : K) (m : Multiset (Row H σ)) : Multiset (Row H' σ') :=
  (f (pointTable k m)).rows k

/-- Representation: a key-local `f` *is* the fiber map of its witnessed action.
This direction needs only key-locality -- split-invariance is not used. -/
theorem keyLocal_eq_fiberMap [DecidableEq K] {f : Table K H σ → Table K H' σ'}
    (hf : KeyLocal f) : f = fiberMap (fiberOf f) := by
  funext T
  apply Table.ext_rows
  intro k
  show (f T).rows k = (f (pointTable k (T.rows k))).rows k
  exact hf T (pointTable k (T.rows k)) k (by simp)

/-- `x = x + x` forces `x = 0` in a multiset (compare cardinalities). -/
theorem multiset_self_add {α : Type _} {x : Multiset α} (h : x = x + x) : x = 0 := by
  have hc : Multiset.card x = Multiset.card x + Multiset.card x := by
    have := congrArg Multiset.card h
    rwa [Multiset.card_add] at this
  exact Multiset.card_eq_zero.mp (by omega)

/-- A split-invariant operation maps the empty table to the empty table: feeding
it `∅ = ∅ + ∅` gives `f ∅ = f ∅ + f ∅`, which forces `f ∅` empty.  Stated with a
possibly different output key type, so it serves both the key-preserving
(`fiberOf_strict`) and key-changing (`reindexFiberOf_strict`) cases. -/
theorem splitInvariant_empty {f : Table K H σ → Table K' H' σ'} (hf : SplitInvariant f)
    (k : K') : (f ⟨fun _ => 0⟩).rows k = 0 := by
  have hdis : Disjoint (⟨fun _ => 0⟩ : Table K H σ) ⟨fun _ => 0⟩ := fun _ => Or.inl rfl
  have hb : bind (⟨fun _ => 0⟩ : Table K H σ) ⟨fun _ => 0⟩ = ⟨fun _ => 0⟩ := by
    apply Table.ext_rows; intro k; simp [bind]
  have h := hf ⟨fun _ => 0⟩ ⟨fun _ => 0⟩ hdis
  rw [hb] at h
  have hrow := congrArg (fun U => Table.rows U k) h
  simp only [bind] at hrow
  exact multiset_self_add hrow

/-- Hence the witnessed action of a split-invariant operation is strict. -/
theorem fiberOf_strict [DecidableEq K] {f : Table K H σ → Table K H' σ'}
    (hf : SplitInvariant f) : Strict (fiberOf f) := by
  intro k
  unfold fiberOf
  have hpt : pointTable k (0 : Multiset (Row H σ)) = ⟨fun _ => 0⟩ := by
    apply Table.ext_rows; intro k'; simp [pointTable]
  rw [hpt]
  exact splitInvariant_empty hf k

/-- **Safe completeness (key-preserving fragment).**  A key-preserving operation
is split-invariant and key-local *iff* it is a strict `fiberMap`.  So the
split-invariant, key-local transformations are *exactly* the strict fiber maps:
`fiberMap` is their universal form, and `map`/`aggregate` are the two principal
generators (`map_eq_fiberMap`, `aggregate_eq_fiberMap`).  Nothing safe is missing
and nothing unsafe sneaks in. -/
theorem splitInvariant_keyLocal_iff_fiberMap [DecidableEq K]
    {f : Table K H σ → Table K H' σ'} :
    (SplitInvariant f ∧ KeyLocal f) ↔ ∃ Φ, Strict Φ ∧ f = fiberMap Φ := by
  constructor
  · rintro ⟨hSI, hKL⟩
    exact ⟨fiberOf f, fiberOf_strict hSI, keyLocal_eq_fiberMap hKL⟩
  · rintro ⟨Φ, hΦ, rfl⟩
    exact ⟨fiberMap_splitInvariant hΦ, fiberMap_keyLocal Φ⟩

/-! ## Sharpness: both hypotheses of the characterization are necessary

Together with the separations already in `Table.lean` (`aggregate_not_bindHom`,
`project_not_preservesDisjoint`, `pivot_not_splitInvariant`) these pin down the
boundaries of the safe fragment: an independence matrix in which no condition is
redundant. -/

/-- Strictness is necessary: a `fiberMap` whose action fabricates a row for the
empty fiber (here a constant singleton) is not split-invariant. -/
theorem fiberMap_nonstrict_not_splitInvariant :
    ¬ SplitInvariant
        (fiberMap (K := Unit) (H := Unit) (σ := fun _ => Unit)
          (H' := Unit) (σ' := fun _ => Unit)
          (fun _ _ => {fun _ => none})) := by
  intro h
  have hT := h ⟨fun _ => 0⟩ ⟨fun _ => 0⟩ (fun _ => Or.inl rfl)
  apply_fun (fun U => (U.rows ()).card) at hT
  simp [fiberMap, bind] at hT

/-- Swap the two keys of a `Bool`-indexed table. -/
def keySwap (T : Table Bool H σ) : Table Bool H σ := ⟨fun b => T.rows (!b)⟩

/-- `keySwap` *is* split-invariant (it is even a bind-homomorphism): it just
relabels keys, and union is computed key-by-key either way. -/
theorem keySwap_splitInvariant : SplitInvariant (keySwap (H := H) (σ := σ)) := by
  intro T₀ T₁ _
  apply Table.ext_rows
  intro b
  simp [keySwap, bind]

/-- Key-locality is necessary: `keySwap` is split-invariant yet not key-local --
its output at a key reads the *other* key -- so it is not a `fiberMap`.  This is
why the characterization needs key-locality as a separate hypothesis. -/
theorem keySwap_not_keyLocal :
    ¬ KeyLocal (keySwap (H := Unit) (σ := fun _ => Unit)) := by
  intro h
  have hcontra := h ⟨fun b => bif b then 0 else {fun _ => none}⟩ ⟨fun _ => 0⟩ true rfl
  simp [keySwap] at hcontra

/-! ## Verbs: a representative slice of "all useful changes", in the primitives

Each verb below is defined purely in terms of the `Table.lean` operations, with
its split-safety machine-checked when it holds.  This is the concrete evidence
for Layer 1: the practical dataframe/SQL verb set lives inside the algebra, and
the leakage-safe verbs are exactly the `SplitSafe` ones. -/

/-- `filter` (dplyr `filter`, relational selection): keep the rows satisfying a
predicate.  A `map`, hence split-safe. -/
def filterRows (p : K → Row H σ → Bool) : Table K H σ → Table K H σ :=
  map (fun k f => if p k f then {f} else 0)

theorem filterRows_splitSafe (p : K → Row H σ → Bool) :
    SplitSafe (filterRows (σ := σ) p) := map_splitSafe _

/-- `mutate` (dplyr `mutate`, relational extension): add a derived column.  A
`map`, hence split-safe. -/
def mutateCol (g : K → Row H σ → V) (T : Table K H σ) :
    Table K (H ⊕ Unit) (Sum.elim σ (fun _ => V)) :=
  map (fun k f => {Row.elim f (fun _ => some (g k f))}) T

theorem mutateCol_splitSafe (g : K → Row H σ → V) :
    SplitSafe (mutateCol (σ := σ) g) := by
  unfold mutateCol; exact map_splitSafe _

/-- `anti_join` / set difference against a fixed table: keep the left rows with
*no* match on the right.  This is the operation that recovers difference, the one
classical relational verb not among the positive generators -- and it is here, as
a `map`, hence split-safe.  No separate primitive is needed. -/
def antiJoin (key : K → U) (right : Table U G τ) (T : Table K H σ) : Table K H σ :=
  map (fun k f => if (right.rows (key k)).card = 0 then {f} else 0) T

theorem antiJoin_splitSafe (key : K → U) (right : Table U G τ) :
    SplitSafe (antiJoin (σ := σ) key right) := by
  unfold antiJoin; exact map_splitSafe _

/-- `distinct` (dplyr `distinct`, duplicate elimination): dedup each key's bag.
It is neither a per-row `map` nor a single-row `aggregate`, but it *is* a strict
`fiberMap`, so it is split-safe directly by `fiberMap_splitSafe` -- a concrete
verb showing `fiberMap` earns its keep as the universal safe primitive. -/
def distinct [DecidableEq (Row H σ)] (T : Table K H σ) : Table K H σ :=
  fiberMap (fun _ m => m.dedup) T

theorem distinct_splitSafe [DecidableEq (Row H σ)] :
    SplitSafe (distinct (K := K) (H := H) (σ := σ)) :=
  fiberMap_splitSafe (fun _ => Multiset.dedup_zero)

/-! ## Extending the characterization to key-changing operations

A `fiberMap` keeps the key.  The safe *key-changing* operations (`ungroup`,
`unpivot`) still read each output key from a *single* input key, related by a
function `r : K' → K` from output keys to input keys.  We capture that as
`reindexMap` and lift the whole characterization to it; `fiberMap` is the `r = id`
case.  `project` is different in kind -- one output key reads a whole *fiber* of
input keys -- so it gets the dual `gatherMap` form, which is split-invariant when
its combiner is additive but is exactly the form that fails to preserve
disjointness.  Together these place every operation of the algebra. -/

/-! ### Pullback form: `reindexMap` (safe key-changing operations) -/

/-- A *reindexing fiber map* along `r : K' → K`: the output bag at key `k'` is a
strict-ready function of the input bag at the single key `r k'`.  This is the
universal shape of a split-invariant operation that reads each output key from
one input key.  `fiberMap` is the `r = id` case (`fiberMap_eq_reindexMap`);
`ungroup` and `unpivot` are the `r = Prod.fst` cases. -/
def reindexMap (r : K' → K) (Φ : K' → Multiset (Row H σ) → Multiset (Row H' σ'))
    (T : Table K H σ) : Table K' H' σ' :=
  ⟨fun k' => Φ k' (T.rows (r k'))⟩

/-- `fiberMap` is the identity-reindexing case. -/
theorem fiberMap_eq_reindexMap (Φ : K → Multiset (Row H σ) → Multiset (Row H' σ')) :
    fiberMap Φ = reindexMap id Φ := rfl

/-- A strict `reindexMap` is split-invariant: at each output key `k'` the relevant
input key `r k'` has one empty summand under disjointness, and strictness makes
folding the union the same as folding the nonempty side. -/
theorem reindexMap_splitInvariant (r : K' → K)
    {Φ : K' → Multiset (Row H σ) → Multiset (Row H' σ')} (hΦ : Strict Φ) :
    SplitInvariant (reindexMap r Φ) := by
  intro T₀ T₁ hdisj
  apply Table.ext_rows
  intro k'
  have hk := hΦ k'
  simp only [reindexMap, bind]
  rcases hdisj (r k') with h | h
  · rw [h]; simp [hk]
  · rw [h]; simp [hk]

/-- A strict `reindexMap` preserves disjointness: an empty input fiber at `r k'`
yields an empty output fiber at `k'`. -/
theorem reindexMap_preservesDisjoint (r : K' → K)
    {Φ : K' → Multiset (Row H σ) → Multiset (Row H' σ')} (hΦ : Strict Φ) :
    PreservesDisjoint (reindexMap r Φ) := by
  intro T₀ T₁ hdisj k'
  rcases hdisj (r k') with h | h
  · exact Or.inl (by simp [reindexMap, h, hΦ k'])
  · exact Or.inr (by simp [reindexMap, h, hΦ k'])

/-- Hence a strict `reindexMap` is `SplitSafe`: the safe key-changing operations
compose into split-invariant pipelines just like the key-preserving ones. -/
theorem reindexMap_splitSafe (r : K' → K)
    {Φ : K' → Multiset (Row H σ) → Multiset (Row H' σ')} (hΦ : Strict Φ) :
    SplitSafe (reindexMap r Φ) :=
  ⟨reindexMap_preservesDisjoint r hΦ, reindexMap_splitInvariant r hΦ⟩

/-- Locality along `r`: each output key `k'` depends only on the input at `r k'`.
For `r = id` this is exactly `KeyLocal`. -/
def ReindexLocal (r : K' → K) (f : Table K H σ → Table K' H' σ') : Prop :=
  ∀ (T T' : Table K H σ) (k' : K'),
    T.rows (r k') = T'.rows (r k') → (f T).rows k' = (f T').rows k'

/-- The fiber action witnessed by an `r`-local operation: run it on a table
supported at the single input key `r k'`, and read off the output key `k'`. -/
def reindexFiberOf [DecidableEq K] (r : K' → K) (f : Table K H σ → Table K' H' σ')
    (k' : K') (m : Multiset (Row H σ)) : Multiset (Row H' σ') :=
  (f (pointTable (r k') m)).rows k'

/-- Representation: an `r`-local operation *is* the `reindexMap` of its witnessed
action (needs only `r`-locality). -/
theorem reindexLocal_eq_reindexMap [DecidableEq K] (r : K' → K)
    {f : Table K H σ → Table K' H' σ'} (hf : ReindexLocal r f) :
    f = reindexMap r (reindexFiberOf r f) := by
  funext T
  apply Table.ext_rows
  intro k'
  show (f T).rows k' = (f (pointTable (r k') (T.rows (r k')))).rows k'
  exact hf T (pointTable (r k') (T.rows (r k'))) k' (by simp)

/-- The witnessed action of a split-invariant operation is strict. -/
theorem reindexFiberOf_strict [DecidableEq K] (r : K' → K)
    {f : Table K H σ → Table K' H' σ'} (hf : SplitInvariant f) :
    Strict (reindexFiberOf r f) := by
  intro k'
  unfold reindexFiberOf
  have hpt : pointTable (r k') (0 : Multiset (Row H σ)) = ⟨fun _ => 0⟩ := by
    apply Table.ext_rows; intro k''; simp [pointTable]
  rw [hpt]
  exact splitInvariant_empty hf k'

/-- **Safe completeness (key-changing fragment).**  Along any `r : K' → K`, an
operation is split-invariant and `r`-local *iff* it is a strict `reindexMap` over
`r`.  This is the full generalization of `splitInvariant_keyLocal_iff_fiberMap`
(its `r = id` instance): the split-invariant, single-source operations are
exactly the strict reindex maps, with `ungroup` and `unpivot` as instances
(`ungroup_eq_reindexMap`, `unpivot_eq_reindexMap`). -/
theorem splitInvariant_reindexLocal_iff_reindexMap [DecidableEq K] (r : K' → K)
    {f : Table K H σ → Table K' H' σ'} :
    (SplitInvariant f ∧ ReindexLocal r f) ↔ ∃ Φ, Strict Φ ∧ f = reindexMap r Φ := by
  constructor
  · rintro ⟨hSI, hRL⟩
    exact ⟨reindexFiberOf r f, reindexFiberOf_strict r hSI, reindexLocal_eq_reindexMap r hRL⟩
  · rintro ⟨Φ, hΦ, rfl⟩
    refine ⟨reindexMap_splitInvariant r hΦ, ?_⟩
    intro T T' k' hk
    simp only [reindexMap]
    rw [hk]

/-! ### `ungroup` and `unpivot` are reindex maps

Both read each output key `(k, ·)` from the single input key `k`, so each is a
`reindexMap` along `Prod.fst`.  This gives a second, uniform proof of their
split-safety straight from `reindexMap_splitSafe`. -/

theorem unpivot_eq_reindexMap :
    unpivot (K := K) (N := N) (V := V)
      = reindexMap Prod.fst (fun (p : K × N) m => m.map (fun f => fun _ => f p.2)) := rfl

example : SplitSafe (unpivot (K := K) (N := N) (V := V)) := by
  rw [unpivot_eq_reindexMap]
  exact reindexMap_splitSafe Prod.fst (by intro _; simp)

theorem ungroup_eq_reindexMap {β : Type} [DecidableEq β] :
    ungroup (K := K) (H := H) (σ := σ) (β := β)
      = reindexMap Prod.fst (fun (p : K × β) m => m.bind (fun f =>
          let v : Cell β := f (Sum.inr ())
          match v with
          | some w => if w = p.2 then {fun h => f (Sum.inl h)} else 0
          | none => 0)) := rfl

example {β : Type} [DecidableEq β] :
    SplitSafe (ungroup (K := K) (H := H) (σ := σ) (β := β)) := by
  rw [ungroup_eq_reindexMap]
  exact reindexMap_splitSafe Prod.fst (by intro _; simp)

/-! ### Merge form: `gatherMap` (the key-merging boundary, `project`)

`project` does not fit `reindexMap`: one output key `k` reads the whole fiber
`{(k, d) : d}` of input keys.  We capture that as `gatherMap`.  When its combiner
is additive in the fiber it is a `BindHom` (hence split-invariant), which is why
`project` is split-invariant -- but it is precisely this many-to-one shape that
fails to preserve disjointness (two rows a split separates by `d` collapse onto
the same output key), so `gatherMap` is *not* `SplitSafe`.  This is the formal
boundary between the safe key-changing operations (`reindexMap`) and the unsafe
key-merging one (`project`), the latter already witnessed by
`project_not_preservesDisjoint`. -/

/-- An output key `k` reads and combines the whole fiber `{T.rows (k, d) : d}`. -/
def gatherMap [Fintype D] (Ψ : K → (D → Multiset (Row H σ)) → Multiset (Row H' σ'))
    (T : Table (K × D) H σ) : Table K H' σ' :=
  ⟨fun k => Ψ k (fun d => T.rows (k, d))⟩

/-- The combiner is additive when it distributes over pointwise union of fibers. -/
def AdditiveGather [Fintype D]
    (Ψ : K → (D → Multiset (Row H σ)) → Multiset (Row H' σ')) : Prop :=
  ∀ (k : K) (fam fam' : D → Multiset (Row H σ)),
    Ψ k (fun d => fam d + fam' d) = Ψ k fam + Ψ k fam'

/-- An additive `gatherMap` is a bind-homomorphism, hence split-invariant. -/
theorem gatherMap_bindHom [Fintype D]
    {Ψ : K → (D → Multiset (Row H σ)) → Multiset (Row H' σ')} (hΨ : AdditiveGather Ψ) :
    BindHom (gatherMap Ψ) := by
  intro T₀ T₁
  apply Table.ext_rows
  intro k
  simp only [gatherMap, bind]
  exact hΨ k _ _

/-- `project` is a `gatherMap`: it sums each fiber's mapped rows. -/
theorem project_eq_gatherMap [Fintype D] :
    project (K := K) (H := H) (σ := σ) (D := D)
      = gatherMap (fun (_k : K) (fam : D → Multiset (Row H σ)) =>
          ∑ d : D, (fam d).map (fun f => Row.elim f (fun _ => some d))) := rfl

/-- And its combiner is additive -- so `project` is a `BindHom` by the uniform
`gatherMap` route (compare `project_bindHom`). -/
theorem project_additiveGather [Fintype D] :
    AdditiveGather (fun (_k : K) (fam : D → Multiset (Row H σ)) =>
      ∑ d : D, (fam d).map (fun f => Row.elim f (fun (_ : Unit) => some d))) := by
  intro k fam fam'
  simp only [Multiset.map_add]
  exact Finset.sum_add_distrib

end Mensura
